# Generated by Django 3.1.7 on 2021-02-24 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menssalista'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovMenssalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('menssalista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menssalista')),
            ],
        ),
    ]
